import { chromium } from "@playwright/test";
const [url, out, scrollTo] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 760 } });
await page.goto(url, { waitUntil: "networkidle" });
await page.evaluate((y) => window.scrollTo(0, +y), scrollTo);
await page.waitForTimeout(300);
await page.screenshot({ path: out });
await browser.close();
console.log("saved", out);
